"""added nullable false to constraints pwlength

Revision ID: 9890718af6ab
Revises: ab57ea33811d
Create Date: 2021-06-02 12:17:12.250086

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9890718af6ab'
down_revision = 'ab57ea33811d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('constraints', 'pw_length',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('constraints', 'pw_length',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
