"""empty message

Revision ID: 125dcf2f7b23
Revises: 881027dde40a
Create Date: 2021-06-28 16:02:53.130664

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '125dcf2f7b23'
down_revision = '881027dde40a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('options',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('allow_ls', sa.Boolean(), nullable=True),
    sa.Column('hints', sa.Boolean(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('options')
    # ### end Alembic commands ###
