"""add generators and constraints

Revision ID: e6f3ea18caa0
Revises: ffdc0a98111c
Create Date: 2021-06-02 12:11:42.677797

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e6f3ea18caa0'
down_revision = 'ffdc0a98111c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('generators',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=40), nullable=False),
    sa.Column('seed', sa.Integer(), nullable=False),
    sa.Column('iteration', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('constraints',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('generator_id', sa.Integer(), nullable=False),
    sa.Column('uppercase_letters', sa.String(length=26), nullable=True),
    sa.Column('lowercase_letters', sa.String(length=26), nullable=True),
    sa.Column('numbers', sa.String(length=10), nullable=True),
    sa.Column('symbols', sa.String(), nullable=True),
    sa.Column('pw_length', sa.Integer(), nullable=True),
    sa.Column('required_uppercase', sa.Integer(), nullable=True),
    sa.Column('required_numbers', sa.Integer(), nullable=True),
    sa.Column('required_symbols', sa.Integer(), nullable=True),
    sa.Column('allow_duplicates', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['generator_id'], ['generators.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('constraints')
    op.drop_table('generators')
    # ### end Alembic commands ###
