"""added nullable false to constraints

Revision ID: ab57ea33811d
Revises: e6f3ea18caa0
Create Date: 2021-06-02 12:16:28.604345

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ab57ea33811d'
down_revision = 'e6f3ea18caa0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('constraints', 'allow_duplicates',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('constraints', 'lowercase_letters',
               existing_type=sa.VARCHAR(length=26),
               nullable=False)
    op.alter_column('constraints', 'numbers',
               existing_type=sa.VARCHAR(length=10),
               nullable=False)
    op.alter_column('constraints', 'required_numbers',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('constraints', 'required_symbols',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('constraints', 'required_uppercase',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('constraints', 'symbols',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('constraints', 'uppercase_letters',
               existing_type=sa.VARCHAR(length=26),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('constraints', 'uppercase_letters',
               existing_type=sa.VARCHAR(length=26),
               nullable=True)
    op.alter_column('constraints', 'symbols',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('constraints', 'required_uppercase',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('constraints', 'required_symbols',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('constraints', 'required_numbers',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('constraints', 'numbers',
               existing_type=sa.VARCHAR(length=10),
               nullable=True)
    op.alter_column('constraints', 'lowercase_letters',
               existing_type=sa.VARCHAR(length=26),
               nullable=True)
    op.alter_column('constraints', 'allow_duplicates',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###
