"""added secret

Revision ID: 45a9bac3d087
Revises: 881027dde40a
Create Date: 2021-06-08 15:50:54.390375

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '45a9bac3d087'
down_revision = '881027dde40a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('secret', sa.String(length=255), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'secret')
    # ### end Alembic commands ###
